//HintName: LiveResx.Avalonia.DynamicResources.g.cs
// <auto-generated/>
//  _      _           _____                                    _             _       
// | |    (_)         |  __ \                    /\            | |           (_)      
// | |     ___   _____| |__) |___  _____  __    /  \__   ____ _| | ___  _ __  _  __ _ 
// | |    | \ \ / / _ \  _  // _ \/ __\ \/ /   / /\ \ \ / / _` | |/ _ \| '_ \| |/ _` |
// | |____| |\ V /  __/ | \ \  __/\__ \>  < _ / ____ \ V / (_| | | (_) | | | | | (_| |
// |______|_| \_/ \___|_|  \_\___||___/_/\_(_)_/    \_\_/ \__,_|_|\___/|_| |_|_|\__,_|
//
//  Generated: 2024/01/15 10:00:00 UTC
//  Version:   0.1.0
//
namespace LiveResx.Avalonia
{
    public static class DynamicResources
    {
        public static global::LiveResx.Avalonia.DynamicTranslation HelloWorld { get; } = new global::LiveResx.Avalonia.DynamicTranslation(
            "HelloWorld",
            () => global::Translations.Resources.ResourceManager);
    }
}
