//HintName: LiveResx.Avalonia.TranslateFormatExtension.g.cs
// <auto-generated/>
//  _      _           _____                                    _             _       
// | |    (_)         |  __ \                    /\            | |           (_)      
// | |     ___   _____| |__) |___  _____  __    /  \__   ____ _| | ___  _ __  _  __ _ 
// | |    | \ \ / / _ \  _  // _ \/ __\ \/ /   / /\ \ \ / / _` | |/ _ \| '_ \| |/ _` |
// | |____| |\ V /  __/ | \ \  __/\__ \>  < _ / ____ \ V / (_| | | (_) | | | | | (_| |
// |______|_| \_/ \___|_|  \_\___||___/_/\_(_)_/    \_\_/ \__,_|_|\___/|_| |_|_|\__,_|
//
//  Generated: 2024/01/15 10:00:00 UTC
//  Version:   0.1.0
//
#nullable enable
#pragma warning disable

namespace LiveResx.Avalonia
{
    /// <summary>
    /// Provides a markup extension that returns a <see cref="global::Avalonia.Data.MultiBinding"/>
    /// combining a format-template <see cref="DynamicTranslation"/> with additional data-bound
    /// arguments, enabling localized composite strings that update automatically when the
    /// application culture changes.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("LiveResx.Avalonia.SourceGenerators", "0.1.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed class TranslateFormatExtension
    {
        /// <summary>
        /// Gets or sets the <see cref="DynamicTranslation"/> that provides the format template string.
        /// </summary>
        public global::LiveResx.Avalonia.DynamicTranslation Template { get; set; }

        /// <summary>
        /// Gets the collection of bindings that supply the format arguments.
        /// </summary>
        [global::Avalonia.Metadata.Content]
        public global::System.Collections.Generic.IList<global::Avalonia.Data.IBinding> Bindings { get; } =
            new global::System.Collections.Generic.List<global::Avalonia.Data.IBinding>();

        /// <summary>
        /// Provides the value for the markup extension, returning a <see cref="global::Avalonia.Data.MultiBinding"/>
        /// that applies <see cref="string.Format(string, object[])"/> using the template from
        /// <see cref="Template"/> and the values from <see cref="Bindings"/>.
        /// </summary>
        /// <param name="serviceProvider">The service provider for the markup extension.</param>
        /// <returns>A <see cref="global::Avalonia.Data.MultiBinding"/> that produces the formatted string.</returns>
        public object ProvideValue(global::System.IServiceProvider serviceProvider)
        {
            var mb = new global::Avalonia.Data.MultiBinding();

            foreach (var binding in Bindings)
            {
                mb.Bindings.Add(binding);
            }

            mb.Bindings.Add(new global::Avalonia.Data.Binding("Text")
            {
                Source = Template,
            });
            mb.Converter = new TranslationTemplateConverter(Template);
            return mb;
        }

        private sealed class TranslationTemplateConverter : global::Avalonia.Data.Converters.IMultiValueConverter
        {
            private readonly global::LiveResx.Avalonia.DynamicTranslation _key;

            public TranslationTemplateConverter(global::LiveResx.Avalonia.DynamicTranslation key)
            {
                _key = key;
            }

            public object Convert(
                global::System.Collections.Generic.IList<object> values,
                global::System.Type targetType,
                object parameter,
                global::System.Globalization.CultureInfo culture)
            {
                object[] args;

                if (values.Count <= 1)
                {
                    args = global::System.Array.Empty<object>();
                }
                else
                {
                    args = new object[values.Count - 1];

                    for (var i = 0; i < args.Length; i++)
                    {
                        args[i] = values[i];
                    }
                }
                var template = _key.Text;
                return string.Format(template, args);
            }
        }
    }
}
