//HintName: LiveResx.Avalonia.__LiveResxRegistration.g.cs
// <auto-generated/>
//  _      _           _____                                    _             _       
// | |    (_)         |  __ \                    /\            | |           (_)      
// | |     ___   _____| |__) |___  _____  __    /  \__   ____ _| | ___  _ __  _  __ _ 
// | |    | \ \ / / _ \  _  // _ \/ __\ \/ /   / /\ \ \ / / _` | |/ _ \| '_ \| |/ _` |
// | |____| |\ V /  __/ | \ \  __/\__ \>  < _ / ____ \ V / (_| | | (_) | | | | | (_| |
// |______|_| \_/ \___|_|  \_\___||___/_/\_(_)_/    \_\_/ \__,_|_|\___/|_| |_|_|\__,_|
//
//  Generated: 2024/01/15 10:00:00 UTC
//  Version:   0.1.0
//
#nullable enable
#pragma warning disable

namespace LiveResx.Avalonia
{
    [global::System.CodeDom.Compiler.GeneratedCode("LiveResx.Avalonia.SourceGenerators", "0.1.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static class __LiveResxRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::LiveResx.Avalonia.DynamicLocalization.Instance.Register(
                new global::LiveResx.Avalonia.DynamicTranslation[0],
                _ => { });

            global::LiveResx.Avalonia.DynamicLocalization.Instance.RegisterResource(
                global::LiveResx.Avalonia.DynamicResources.s_CustomLabels);
        }
    }
}
