//HintName: LiveResx.Avalonia.TranslateExtension.g.cs
// <auto-generated/>
//  _      _           _____                                    _             _       
// | |    (_)         |  __ \                    /\            | |           (_)      
// | |     ___   _____| |__) |___  _____  __    /  \__   ____ _| | ___  _ __  _  __ _ 
// | |    | \ \ / / _ \  _  // _ \/ __\ \/ /   / /\ \ \ / / _` | |/ _ \| '_ \| |/ _` |
// | |____| |\ V /  __/ | \ \  __/\__ \>  < _ / ____ \ V / (_| | | (_) | | | | | (_| |
// |______|_| \_/ \___|_|  \_\___||___/_/\_(_)_/    \_\_/ \__,_|_|\___/|_| |_|_|\__,_|
//
//  Generated: 2024/01/15 10:00:00 UTC
//  Version:   0.1.0
//
#nullable enable
#pragma warning disable

namespace LiveResx.Avalonia
{
    /// <summary>
    /// Provides a markup extension that returns a data-binding to a <see cref="DynamicTranslation"/> instance,
    /// enabling automatic UI updates when the application culture changes.
    /// </summary>
    public sealed class TranslateExtension
    {
        private readonly global::LiveResx.Avalonia.DynamicTranslation _translation;

        /// <summary>
        /// Initializes a new instance of the <see cref="TranslateExtension"/> class.
        /// </summary>
        /// <param name="translation">The dynamic translation to bind to.</param>
        public TranslateExtension(global::LiveResx.Avalonia.DynamicTranslation translation)
        {
            _translation = translation;
        }

        /// <summary>
        /// Provides the value for the markup extension, returning a data-binding
        /// to the <c>Text</c> property of the underlying <see cref="DynamicTranslation"/>.
        /// </summary>
        /// <param name="serviceProvider">The service provider for the markup extension.</param>
        /// <returns>A <see cref="global::Avalonia.Data.Binding"/> to <c>DynamicTranslation.Text</c>.</returns>
        public object ProvideValue(global::System.IServiceProvider serviceProvider)
        {
            return new global::Avalonia.Data.Binding("Text")
            {
                Source = _translation,
            };
        }
    }
}