using System.Collections.Generic;

namespace LiveResx.Avalonia.SourceGenerators.Models;

/// <summary>
/// Represents a resource Designer type discovered in the compilation
/// (e.g., <c>Translations.Resources</c> generated by <c>ResXFileCodeGenerator</c>).
/// </summary>
internal sealed record ResourceDesignerType
{
    /// <summary>
    /// Gets the fully qualified name of the resource designer type,
    /// e.g. <c>"Translations.Resources"</c>.
    /// </summary>
    public string FullTypeName { get; }

    /// <summary>
    /// Gets the namespace containing the resource designer type, e.g. <c>"Translations"</c>.
    /// </summary>
    public string Namespace { get; }

    /// <summary>
    /// Gets the short type name, e.g. <c>"Resources"</c>.
    /// </summary>
    public string TypeName { get; }

    /// <summary>
    /// Gets the resource key names discovered from this designer type.
    /// These are the <see cref="string"/> property names that correspond
    /// to entries in the <c>.resx</c> file.
    /// </summary>
    public IReadOnlyList<string> ResourceKeys { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="ResourceDesignerType"/> class.
    /// </summary>
    public ResourceDesignerType(
        string fullTypeName,
        string @namespace,
        string typeName,
        IReadOnlyList<string> resourceKeys)
    {
        FullTypeName = fullTypeName;
        Namespace = @namespace;
        TypeName = typeName;
        ResourceKeys = resourceKeys;
    }
}
