using System;
using System.Reflection;

namespace LiveResx.Avalonia.SourceGenerators;

/// <summary>
/// Generates the standardized header comment block prepended to all
/// source files emitted by the <see cref="DynamicTranslationGenerator"/>.
/// </summary>
internal static class GeneratorHeader
{
    private static readonly string? s_version = typeof(DynamicTranslationGenerator)
        .Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()
        ?.InformationalVersion;

    /// <summary>
    /// Produces the header block including the ASCII art banner, generation timestamp,
    /// and generator version.
    /// </summary>
    /// <param name="timestamp">The timestamp to embed in the header. Should be captured
    /// once per compilation for stability.</param>
    /// <returns>A multi-line comment block ending with a blank-line terminator.</returns>
    internal static string Generate(DateTimeOffset timestamp)
    {
        var ts = timestamp.ToString("yyyy/MM/dd HH:mm:ss 'UTC'");

        return $"""
            // <auto-generated/>
            //  _      _           _____                                    _             _       
            // | |    (_)         |  __ \                    /\            | |           (_)      
            // | |     ___   _____| |__) |___  _____  __    /  \__   ____ _| | ___  _ __  _  __ _ 
            // | |    | \ \ / / _ \  _  // _ \/ __\ \/ /   / /\ \ \ / / _` | |/ _ \| '_ \| |/ _` |
            // | |____| |\ V /  __/ | \ \  __/\__ \>  < _ / ____ \ V / (_| | | (_) | | | | | (_| |
            // |______|_| \_/ \___|_|  \_\___||___/_/\_(_)_/    \_\_/ \__,_|_|\___/|_| |_|_|\__,_|
            //
            //  Generated: {ts}
            //  Version:   {Version}
            //
            #nullable enable
            #pragma warning disable


            """;
    }

    /// <summary>
    /// Produces a <see cref="System.CodeDom.Compiler.GeneratedCodeAttribute"/> for the
    /// <see cref="DynamicTranslationGenerator"/> with the current assembly version.
    /// </summary>
    /// <returns>The attribute text to place before a class declaration.</returns>
    internal static string GeneratedCodeAttribute =>
        $"""[global::System.CodeDom.Compiler.GeneratedCode("LiveResx.Avalonia.SourceGenerators", "{Version}")]""";

    /// <summary>
    /// Gets the assembly version used for the <see cref="System.CodeDom.Compiler.GeneratedCodeAttribute"/>.
    /// </summary>
    private static string Version => s_version ?? "0.0.0.0";
}
